FROM nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
    tmux \
    wget \
    vim \   
    python3.8.10 \
    python3-distutils \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3.8.10 10 \
    && wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py && rm get-pip.py \
    && rm -rf /var/lib/apt/lists/*

# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Asia/Singapore /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# Expose ports
EXPOSE 6006
EXPOSE 6379

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user 
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user
WORKDIR /home/user
# Install zsh related
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.1/zsh-in-docker.sh)" -- \
    -t ys \
    -p git \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -p https://github.com/zsh-users/zsh-history-substring-search \
    -p https://github.com/zsh-users/zsh-syntax-highlighting
RUN sudo chsh -s /bin/zsh

# Install pytorch
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html \
    && pip install --no-cache-dir pylint autopep8 ipykernel numpy

# set tmux
RUN sudo echo "set-option -g default-shell /bin/zsh" >> ~/.tmux.conf

# Set the default command to zsh
ENTRYPOINT [ "/bin/zsh" ]
CMD ["-l"]